In [2]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('logs/Cora_mask1.csv')
data2 = pd.read_csv('logs/Cora_mask2.csv')
# 去除最后一行
data = data[:-1]
data2 = data2[:-1]

# 在同一张图上画多个曲线
# 设置图的大小和清晰度
plt.figure(dpi=600,figsize=(20, 5))
plt.plot(data['epoch'], data['loss'], label='mask1')
plt.plot(data2['epoch'], data2['loss'], label='mask2')
plt.legend()
plt.show()

ModuleNotFoundError: No module named 'pandas'

In [2]:
import dgl
import torch

# 构建有向图
g = dgl.DGLGraph()
g.add_nodes(5)
g.add_edges([0, 1, 1, 2, 3, 4], [1, 2, 3, 0, 4, 0]) # 添加边

# 定义输入节点列表
input_nodes = [0, 3]

# 将邻接矩阵转换为 COO 格式，并移动到 GPU 上
device = torch.device('cuda')
adj = g.adjacency_matrix().coalesce().to(device)

# 使用索引操作获取所有与输入节点相连的节点
rows, cols, _ = adj.coo()
neighs = cols[rows == torch.tensor(input_nodes).to(device)]

# 打印结果
print(neighs)

/opt/conda/envs/graph/lib/python3.8/site-packages/dgl/heterograph.py:72: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)`'


AttributeError: 'Tensor' object has no attribute 'coo'

In [41]:
# import dgl

# # 创建一个包含浮点数节点索引的张量
# node_indices = torch.tensor([0.0, 1.0, 2.0])

# # 将节点索引张量转换为整数类型
# node_indices = node_indices.long()

# # 创建一个图对象
# num_nodes = 5
# edges = [(0,1),(1,2),(1,3),(2,4),(3,0),(3,2),  (1,0),(2,1),(3,1),(4,2),(0,3),(2,3)] 
# graph = dgl.graph(edges, num_nodes=num_nodes)


# # 将图对象转换为邻接矩阵
# adj_matrix =graph.adjacency_matrix()

# # 选择节点3
# node = torch.tensor([3])

# # 获得节点3的邻居
# neighbors = adj_matrix[node]

# print(neighbors)

import dgl
import torch

# 创建一个图对象
num_nodes = 5
edges = [(0,1),(1,2),(1,3),(2,4),(3,0),(3,2), (1,0),(2,1),(3,1),(4,2),(0,3),(2,3)] 
graph = dgl.graph(edges, num_nodes=num_nodes)

# 选择多个节点
nodes = torch.tensor([1, 2, 3])

# 将图对象转换为邻接矩阵
adj_matrix = graph.adjacency_matrix()

# 获得这些节点的邻居
neighbors = adj_matrix[nodes].to_dense()

# 将邻居节点合并为一个无重复的点集
unique_neighbors, _ = torch.unique(neighbors, dim=1, return_inverse=True)

print(unique_neighbors.squeeze())


NotImplementedError: Could not run 'aten::index.Tensor' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::index.Tensor' is only available for these backends: [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/build/aten/src/ATen/RegisterCPU.cpp:18433 [kernel]
CUDA: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/build/aten/src/ATen/RegisterCUDA.cpp:26496 [kernel]
QuantizedCPU: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1068 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ADInplaceOrView: fallthrough registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradLazy: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradXPU: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradMLC: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradHPU: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradNestedTensor: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
AutogradPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/VariableType_1.cpp:9548 [autograd kernel]
Tracer: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/generated/TraceType_1.cpp:10664 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]


In [85]:
import dgl
import torch

# 创建一个图对象
num_nodes = 5
edges = [(0,1),(1,2),(1,3),(2,4),(3,0),(3,2), (1,0),(2,1),(3,1),(4,2),(0,3),(2,3)] 
graph = dgl.graph(edges, num_nodes=num_nodes)
graph.to(torch.device('cuda'))

# 选择多个节点
nodes = torch.tensor([0])

def get_neighbors(graph, nodes):


    assert type(nodes) == torch.Tensor, 'nodes must be a tensor'
    # 将图对象转换为邻接矩阵
    adj_matrix = graph.adjacency_matrix()

    print(nodes)
    # 获得这些节点的邻居
    neighbors = adj_matrix.index_select(0, nodes)


    print(neighbors)

    # 压缩稀疏矩阵
    neighbors = neighbors.coalesce()

    neighbors.indices()[1]

    # unique_neighbors = torch.unique(neighbors.indices()[1])

    return unique_neighbors

# 多重递归获得邻居节点
def get_all_neighbors(graph, nodes, depth):
    if depth == 0:
        return nodes
    else:
        neighbors = get_neighbors(graph, nodes)
        return get_all_neighbors(graph, neighbors, depth-1)

# 获得节点0的所有邻居
all_neighbors = get_all_neighbors(graph, nodes, 1)
all_neighbors

# # 将邻居节点合并为一个无重复的点集
# unique_neighbors, _ = torch.unique(neighbors, dim=1, return_inverse=True)

# print(unique_neighbors.squeeze())

tensor([0])
tensor(indices=tensor([[0, 0],
                       [1, 3]]),
       values=tensor([1., 1.]),
       size=(1, 5), nnz=2, layout=torch.sparse_coo)


tensor([0, 1, 2, 3, 4])

In [111]:

def get_neighbors(graph:dgl.DGLGraph, nodes:torch.Tensor):
    """获得一个中心点列表中所有中心点的邻居，不包括中心点本身，且去重

    Args:
        graph (dgl.DGLGraph): 图对象
        nodes (torch.Tensor): 中心节点张量，1*nodes_num

    Returns:
        torch.Tensor: 所有中心点的邻居节点组成的无重复节点张量, 1*neighbors_num
    """
    assert nodes.is_cuda == True
    # print(type(graph))
    adj_matrix = graph.adjacency_matrix()
    # 判断adj_matrix的是否在GPU上
    # print(adj_matrix.is_cuda)
    adj_matrix = adj_matrix.to(nodes.device)
    # adj_matrix = adj_matrix.to(nodes.device)
    # print(adj_matrix.device)
    assert adj_matrix.is_cuda == True

    # 获得这些节点的邻居
    neighbors = adj_matrix.index_select(0, nodes)
    # 压缩稀疏矩阵
    neighbors = neighbors.coalesce()
    # neighbors.indices()返回一个2*neighbors_num的矩阵，2 * neighbors_num，第二行是所有邻居节点标号的横向拼接
    unique_neighbors = torch.unique(neighbors.indices()[1])

    return unique_neighbors

# 多重递归获得邻居节点
def get_all_neighbors(graph:dgl.DGLGraph, nodes:torch.Tensor, depth:int):
    """多重递归获得邻居节点集合张量（逻辑上是集合，物理数据结构为torch.Tensor），且去重

    Args:
        graph (dgl.DGLGraph): 输入图
        nodes (torch.Tensor): 中心节点集合张量，1*nodes_num
        depth (int): 递归深度，为0时相当于点遮盖，直接返回nodes

    Returns:
        torch.Tensor: 所有中心点的邻居节点组成的无重复节点张量, 1*neighbors_num
    """
    if depth == 0:
        return nodes
    else:
        neighbors = get_neighbors(graph, nodes)
        neighbors = torch.cat([nodes, neighbors])
        neighbors = torch.unique(neighbors)
        return get_all_neighbors(graph, neighbors, depth-1)


In [9]:
!bash ;conda activate graph

(base) ]0;root@84dc942e2771: ~/models/SMCLroot@84dc942e2771:~/models/SMCL# ^C

(base) ]0;root@84dc942e2771: ~/models/SMCLroot@84dc942e2771:~/models/SMCL# 

In [3]:
import dgl

def get_neighbors(graph:dgl.DGLGraph, nodes:torch.Tensor):
    """获得一个中心点列表中所有中心点的邻居，不包括中心点本身，且去重
    Args:
        graph (dgl.DGLGraph): 图对象
        nodes (torch.Tensor): 中心节点张量，1*nodes_num
    Returns:
        torch.Tensor: 所有中心点的邻居节点组成的无重复节点张量, 1*neighbors_num
    """
    assert nodes.is_cuda == True
    # print(type(graph))
    adj_matrix = graph.adjacency_matrix()
    # 判断adj_matrix的是否在GPU上
    # print(adj_matrix.is_cuda)
    adj_matrix = adj_matrix.to(nodes.device)
    # adj_matrix = adj_matrix.to(nodes.device)
    # print(adj_matrix.device)
    assert adj_matrix.is_cuda == True

    # 获得这些节点的邻居
    neighbors = adj_matrix.index_select(0, nodes)
    # 压缩稀疏矩阵
    neighbors = neighbors.coalesce()
    # neighbors.indices()返回一个2*neighbors_num的矩阵，2 * neighbors_num，第二行是所有邻居节点标号的横向拼接
    unique_neighbors = torch.unique(neighbors.indices()[1])

    return unique_neighbors

# 多重递归获得邻居节点
def get_all_neighbors(graph:dgl.DGLGraph, nodes:torch.Tensor, depth:int):
    """多重递归获得邻居节点集合张量（逻辑上是集合，物理数据结构为torch.Tensor），且去重
    Args:
        graph (dgl.DGLGraph): 输入图
        nodes (torch.Tensor): 中心节点集合张量，1*nodes_num
        depth (int): 递归深度，为0时相当于点遮盖，直接返回nodes
    Returns:
        torch.Tensor: 所有中心点的邻居节点组成的无重复节点张量, 1*neighbors_num
    """
    if depth == 0:
        return nodes
    else:
        neighbors = get_neighbors(graph, nodes)
        return get_all_neighbors(graph, neighbors, depth-1)



In [13]:
import torch
import networkx as nx
import matplotlib.pyplot as plt
import dgl
# import numpy as np

g = dgl.DGLGraph()
g.add_nodes(10)
g.add_edges([0, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 0, 5, 6, 7, 8, 9, 4],
            [1, 2, 3, 0, 4, 5, 6, 7, 8, 9, 0, 1, 2, 6, 7, 8, 9, 3, 4, 5])
g = g.to(torch.device('cuda'))

nodes = torch.tensor([1,5,9],device="cuda")

print(nodes)
print(get_all_neighbors(g,nodes,1))


tensor([1, 5, 9], device='cuda:0')
tensor([2, 3, 4, 7, 8], device='cuda:0')


In [16]:
import numpy as np
# 读取文件中的字符串内容
data = open("./nohup_logs/20230515002301/IMDB-BINARY.log").read()
# 按照换行符和逗号分割字符串
data_ls = data.split("\n")
acc_ls = []
for i in data_ls:
    for j in i.split(","):
        if (j.startswith("Acc")):
            # print(j)
            j.replace("Acc: ","")
            acc = float(j.split(": ")[1])
            acc_ls.append(acc)
# 计算acc的平均值和+/-误差
acc_mean = np.mean(acc_ls)
print("acc_mean: ",acc_mean)
print("acc_max", np.max(acc_ls))
# 计算负误差
acc_minus = acc_mean - np.min(acc_ls)
acc_plus = np.max(acc_ls) - acc_mean
print("acc_minus: ",acc_minus)
print("acc_plus: ",acc_plus)
print(acc_ls)

acc_mean:  0.5002698412698413
acc_max 0.522
acc_minus:  0.025603174603174628
acc_plus:  0.02173015873015871
[0.48933333333333334, 0.4933333333333333, 0.504, 0.5113333333333333, 0.5066666666666666, 0.5, 0.5113333333333333, 0.4913333333333334, 0.5046666666666667, 0.4913333333333333, 0.5133333333333334, 0.484, 0.4953333333333334, 0.5166666666666667, 0.5133333333333333, 0.5033333333333334, 0.5046666666666667, 0.5066666666666668, 0.4986666666666667, 0.4746666666666667, 0.4946666666666667, 0.5013333333333334, 0.5113333333333332, 0.5026666666666666, 0.4953333333333333, 0.49266666666666675, 0.5093333333333334, 0.5079999999999999, 0.4946666666666667, 0.502, 0.4846666666666667, 0.5033333333333333, 0.4873333333333334, 0.49066666666666664, 0.4926666666666667, 0.4993333333333333, 0.502, 0.4966666666666667, 0.522, 0.49800000000000005, 0.4993333333333333, 0.5093333333333333]
